### ISSUE TITLE
TL;DR: Try turning off your ad blocker.

### ISSUE THREAD

**Issue by peeter7** [krasyid822/UnlimitedAIImagesGenerator#1]
I am not using any type of ad blocker or browser extension, yet the issue persists.
![image](https://github.com/user-attachments/assets/8fcefc5f-6f56-4552-99a6-4611d1f9d9b5)

**Comment by krasyid822** [comment]
sorry, because this code not complete. i only copy and paste code from original website using page source browser feature.

**Comment by krasyid822** [comment]
you can view working site in https://perchance.org/ai-text-to-image-generator
